default:
  course_name_long: "Epi/Biostats Summer Institute - Introduction to R for Public Health Researchers 140.604.79"
  course_dates: "June 8-19th, 2026"
  course_time: "8:30 am - 11:50 am ET"
  last_session_time: "10:50 am - 11:50 am ET"
  final_due_date: "June 26th at 11:59 pm ET"
  grades_due: "August 28th"
  holiday: "In recognition of [Juneteenth](https://en.wikipedia.org/wiki/Juneteenth), there will be **no class on June 19th**."
  courseplus_web: "https://courseplus.jhu.edu/core/index.cfm/go/course.home/coid/25840/"
  courseplus_dropboxes: "https://courseplus.jhu.edu/core/index.cfm/go/db:main/coid/25840/" 
  google_survey: "https://forms.gle/aq13Ti3y9w5zsNeu7"
  slack_workspace: "https://intro-to-r-summer2026.slack.com/"
  ta: "Bella Satpathy-Horton (ghorton2 at jhmi.edu)"
  instructors: "[Ahmed Sabit](https://publichealth.jhu.edu/faculty/4412/ahmed-h-sabit) (ahmed.sabit at jhu.edu), [Clifton McKee](https://clifmckee.github.io/) (cmckee7 at jhu.edu)"
  r_version: "(4.6.0 (called 'Because it was There') as of 2026-04-24)"
  r_dl_mac_m1: "https://cran.r-project.org/bin/macosx/sonoma-arm64/base/R-4.6.0-arm64.pkg"
  r_dl_mac_intel: "https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.6.0-x86_64.pkg"
  r_dl_windows: "https://cran.r-project.org/bin/windows/base/R-4.6.0-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2026.05.0-218.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2026.05.0-218.exe"

