---
title: "Syllabus"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Epi/Biostats  Winter Institute - Introduction to R for Public Health Researchers
140.604.73

Class Website: http://jhudatascience.org/intro_to_r/   
CoursePlus: https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/16733/

**Zoom link will be emailed to students.**

Day/Time: June 14-18: 8:30AM-11:50AM on Zoom

Instructors: Carrie Wright (cwrigh60@jhu.edu), Ava Hoffman (ava.hoffman@jhu.edu), and Candace Savonen(csavone1@jhu.edu) 

TAs:  Grant Schumock (gschumo1@jhmi.edu) and Qier Meng(qmeng11@jhmi.edu)


**Communication will mainly occur through Slack and we will email you about how to connect to slack.**


Overview: This course will provide "hands-on" training for learning how to analyze data in the R statistical software package. We will cover data input/output, data management and manipulation, and how to make useful and informative graphics
 
Course Format: Each class will consist of 2 or 3 hour-long modules: each module features a lecture and an R programming lab, where student apply the skills taught in the modules to real data. 

By the end of the course, students should be comfortable:

- Reading data into R
- Recoding and manipulating data
- Using R add-on packages
- Making exploratory plots
- Performing basic statistical tests
- Understanding basic programming syntax
- Creating reproducible R documents

# Tentative Schedule:

## Day 1

- Introduction 
- RStudio 
- Reproducible Research 


## Day 2
- Basic R: Variables/Objects in R
- Data Input/Output 


## Day 3

- Subsetting Data
- Homework 2

## Day 4

- Summarization 
- Data Classes

## Day 5

 
- Data Cleaning
- Homework 3


## Day 6
- Data Manipulation


## Day 7

-  Data Visualization

## Day 8

- Statistics
- Work on Final Project


## Day 9

- Functions
- Good code practices 
- Work on Final Project

### Grading

1. Attendance/Participation: 20%
2. Nightly Homework: 3 x 15%
3. Final "Project": 35%
