---
title: "TA Info for Intro to R"
output: html_document
---

## Summary:

Thank you for your interest in being a TA for our course! 
We like to create a fun environment and we cover lots of material in the course quickly, so we need your help!

The course will be roughly 50% lecture and 50% lab time.

## Logistics:

- **Dates:** always 9 days for the summer and winter institutes (with one day off, either MLK or Juneteenth) 1:30 – 4:50pm Eastern Time, see [here](https://publichealth.jhu.edu/academics/academic-program-finder/accelerated-learning-institutes) for more information.
- **Course GitHub:** https://github.com/jhudsl/intro_to_r
- **Class will be on Zoom** - link will be sent to you
- **Class will have a Slack Workspace** - link will be sent to you
- **CoursePlus** - We mostly use CoursePlus for grades, the course should show up when you log in once you are set up
- **Payment** - There is a stipend for being a TA

 
## Roles:

- **One-on-one Breakout Rooms** - If someone needs/wants extra attention, they typically go to the TA breakout room during lab time.
-  **Office Hours**  - Typically 1 hr per TA per week to allow students more opportunties for help.
- **Answering Live Questions** - Helping to answer questions during class. 
- **Answering Questions Outside Class** - Helping to answer questions outside class hours (on slack) if you see something and are available. (There is no expectation to be available outside office hours and class hours though).
- **Grading HW** - There are 3 Homework Assignments. The Keys are available on the website for the students, we ask that you grade for completeness. Grades should be added to courseplus. 
- **Optional Lecturing** - Some TAs have helped teach a lecture or part of a lecture (using our materials, although updates are possible but we would need to discuss). (There is no expectation for this, but some TAs like the opportunity to practice their lecturing skills.)
- **Optional GitHub Updates** - Some TAs have also helped us make updates to material on GitHub (using a Pull Request), see the contributing doc [here](https://github.com/jhudsl/intro_to_r/blob/main/docs/Contribute.md). (There is no expectation this, but some TAs like the opportunity to practice their GitHub skills.)

## First Steps

- We will need a photo and a description of you for our intro slides, like this: https://jhudatascience.org/intro_to_r/modules/Intro/Intro.html#4 

We really appreciate your help!

 
