---
title: "Homework 3"
author: "Untitled"
date: "January 3, 2019"
output: html_document
---

This is the second homework assignment for Intro to R. You must submit both the RMD and "knitted" HTML files are due before class on Friday (Day 5)

Use this dataset on infant mortality for the following questions: http://johnmuschelli.com/intro_to_r/data/indicatordeadkids35.csv


```{r initiatePackages, message=FALSE}
## you can add more, or change...these are suggestions
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

Questions

1.	Read the data using `read_csv()` and name it `mort`. Create a integer 'year' variable using the column names (using `colnames()` and `as.integer()`), excluding the first column. Rename the first column to "country" using the `rename()` command in `dplyr`.

2.	Reshape the data so that there is a variable named "year" corresponding to year (key) and a column of the mortalities named mortality (value). Hint: use the `tidyr` package and its `gather()` function. Name the output `long` and make `year` a numeric variable. Hint: remember that -COLUMN_NAME removes that column, gather all the columns but country.  

3.	Read in this the tab-delim file: http://johnmuschelli.com/intro_to_r/data/country_pop.txt and call it `pop`, which contains population information on each country (hint: use `read_tsv()`).  Rename the second column to "Country" and the column "% of world population", to "percent"

4.	Determine the population of each country in `pop` using `arrange()`. Get the order of the countries based on this (first is the highest population), then make a variable in the long data set named `sorted` that is the "country"" variable coded as a factor based on this sorted population level from `pop`

5.	Subset `long` based on years 1975-2010, including 1975 and 2010 and call this `long_sub`.  Subset the following countries using `dplyr::filter()` and the %in% operator on the sorted country factor ("sorted") for `long_sub` with
`c("Venezuela", "Bahrain", "Estonia", "Iran", "Thailand", "Chile",  "Western Sahara", "Azerbaijan", "Argentina", "Haiti")`. Lastly, remove missing rows for mortality using `filter()` and `is.na()`.

6.  Plotting: create "spaghetti"/line plots for the countries, using different colors for different countries. The x-axis should be year, and the y-axis should be mortality
