<!-- This document contains code of coduct details that appear multiple places. -->

## Code of Conduct

We would like to create an open, safe, welcoming, diverse, inclusive, intellectually stimulating, and hopefully fun class experience. 

We strive to be a space in which individual differences are respected, so that each individual can reach their fullest potential.

### Guidelines

- Demonstrating empathy and kindness toward other people
- Giving and gracefully accepting constructive feedback
- Avoiding making assumptions about others
- Being respectful of differing opinions, viewpoints, and experiences
- Take the time to consider how your speech and actions may influence others
- Actively seek to acknowledge and respect the boundaries of other members
- Demonstrating academic integrity 
    - Students can work together, but assignments must show unique contributions from the student who turns in the assignment
    - Students can use online resources for help, but assignments must show unique contributions from the student who turns in the assignment - plagiarism is not allowed
    - If students are struggling, reach out to instructors or TAs as early as possible


This applies to emails, surveys, Slack, Zoom, office hours, meetings with other students, instructors, or TAs.

 **Please reach out to a TA or instructor if you witness or experience a violation of the class guidelines or other JHU codes of conduct.**

- **JHU Student Code of Conduct:**   
https://studentaffairs.jhu.edu/policies-guidelines/student-code/  
- **Hopkins School of Medicine:**  
https://www.hopkinsmedicine.org/research/resources/offices-policies/OPC/Research_Integrity/som_code_of_conduct_04302020.pdf   
- **JHSPH Academic Ethics Code:**   
https://www.jhsph.edu/offices-and-services/student-affairs/resources/student-policies/_documents/academic-ethics-code.pdf 

**The University has developed avenues for reporting and for seeking help including:** 

● JHU Sexual Assault Helpline, 410-516-7333 (confidential) 
● Campus Safety and Security, 410-516-7777 
● University Sexual Assault Response and Prevention website 
● Johns Hopkins Compliance Hotline, 844-SPEAK2US (844-733-2528) 
● JHU Office of Institutional Equity 410-516-8075 (nonconfidential) 
● Johns Hopkins Student Assistance Program (JHSAP), 443-287-7000 
● University Health Services - Mental Health (UHS-MS), 410-955-1892 
● The Faculty and Staff Assistance Program (FASAP), 443-997-7000 
